version: "3"
services:
  TDM_backend:
    image: armdocker.rnd.ericsson.se/proj_taf_tdm/tdm-server:${TDM_VERSION}
    container_name: "TDM_backend"
    restart: "always"
    ports:
      - "9443:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=customer
    volumes:
      - /opt/store/volumes/tdm-logs:/var/log/tdm
    depends_on:
      - mongodb
    logging:
      options:
        max-size: "1g"
        max-file: "3"
    links:
      - "taf_ldap:enmteagat"
  mongodb:
    image: mongo:3.2
    restart: "always"
    ports:
     - "27017:27017"
    volumes:
     - /tdmMongoDB/db:/data/db
  cAdvisor:
    image: google/cadvisor:latest
    container_name: "cAdvisor"
    restart: "always"
    stdin_open: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    ports:
      - "9090:8080"
  taf_ldap:
      image:  armdocker.rnd.ericsson.se/proj_taf_te/taf_ldap:${taf_ldap.version}
      container_name: "taf_ldap"
      ports:
        - "3689:389"
      volumes:
        - /etc/openldap:/etc/ldap
        - /var/lib/ldap/:/var/lib/ldap
        - /etc/ldap/prepopulate/:/etc/ldap.dist/prepopulate